train: ../datasets/images/train
val: ../datasets/images/test
test: ../datasets/images/test

nc: 3
names: ['bird', 'drone', 'helicopter']

#  # dataset path
# train: ../datasets/images/train
# val: ../datasets/images/test
# test: ../datasets/images/test
 
# # number of classes
# nc: 15
 
# # class names
# names: ['car', 'Truck', 'Van', 'Long Vehicle','Bus', 'Airliner', 'Propeller Aircraft', 'Trainer Aircraft', 'Chartered Aircraft', 'Fighter Aircraft',\
#         'Others', 'Stair Truck', 'Pushback Truck', 'Helicopter', 'Boat']